# Generated by Django 2.2.5 on 2020-02-15 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200207_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(default='', max_length=40)),
                ('roll_number', models.CharField(default='', max_length=20)),
                ('Announcement', models.TextField()),
                ('Announcement_Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
