# Generated by Django 2.2.5 on 2020-02-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200215_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsannouncement',
            old_name='Announcement_Time',
            new_name='AnnouncementTime',
        ),
        migrations.RenameField(
            model_name='studentsannouncement',
            old_name='roll_number',
            new_name='rollnumber',
        ),
    ]
