# Generated by Django 2.2.5 on 2020-02-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_privateannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsannouncement',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
        ),
    ]
