# Generated by Django 2.2.5 on 2020-02-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentsannouncement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
