# Generated by Django 2.2.5 on 2020-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_candidate_company_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
