# Generated by Django 2.2.5 on 2020-02-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_candidate_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
