# Generated by Django 2.2.5 on 2020-02-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200220_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='eligibility_criteria',
            field=models.ManyToManyField(blank=True, related_name='eligible_companies', to='main.eligible'),
        ),
    ]
