# Generated by Django 2.2.5 on 2020-02-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200220_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selected_Students',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
