# Generated by Django 3.0.3 on 2020-02-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200221_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
