# Generated by Django 3.0.3 on 2020-02-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200221_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm1', models.CharField(choices=[('1', 'Confirm'), ('0', 'Not Confirm')], default='0', max_length=20)),
                ('cand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.candidate')),
            ],
        ),
    ]
